CREATE TABLE ITEM (
  ITEM_ID INTEGER(10) NOT NULL AUTO_INCREMENT,
  ITEM_NAME varchar(20) NOT NULL,
  PRICE INTEGER(11) NOT NULL,
  DESCRIPTION varchar(300) NOT NULL,
  PRIMARY KEY(ITEM_ID)
);

CREATE TABLE USER(
	USER_NAME VARCHAR(20),
	PASSWORD VARCHAR(20),
	PRIMARY KEY(USER_NAME)
);

